### ISSUE TITLE
Feature request: Only specific Gas Station brands

### ISSUE THREAD

**Issue by BoingPlatsch** [Necriso/ScriptableWidgets#1]
Hallo Necriso,
first of all a big thanks to you for your work! It is a nice script and works as intended 👍🏼

Can I ask you for a little feature update? I‘m lucky that I’m allowed to have a company car. Therefor I’m only able to fuel up the car at major gas stations like Shell, ARAL, Agip, Esso, etc.
Is it possible to only get results for specific brands? I tried to figure it out myself, but my coding skills are very basic.

Thanks in advance!

Kind regards
BoingPlatsch alias Florian

**Comment by skjall** [comment]
Not the developer but trying to explain:
The Issue will be that the API doesn't support a brand filter. The script can only load all stations within the radius, ordered by price. It takes this dataset and displays the first entry. Easy Peasy.
Adding a brand filter would mean: After downloading the stations run through all of them and find the brand you are looking for. It occurs, stop and use this entry. If none is found, show some error or the next best station.
IMHO it would work but is not so elegant.

**Comment by BoingPlatsch** [comment]
First of all, thank you for your answer, @Skjall!

If I understand correct, I have to adjust the code in line 99 with “a little” loop through all the items in the list looking for the closest match of a specific brand instead of taking the first entry, right?
`const attr = data.stations[0] `

Can you maybe help me with it? I would be able to do it in Excel VBA but that’s the only coding language I can a bit... 😅

Thanks in advance!

**Comment by skjall** [comment]
Probably yes. My brother only uses Aral because of payback and he asked me for the same. I'll post it here when I have it coded and tested.

**Comment by Necriso** [comment]
Hi @BoingPlatsch 

Widget is ready now.
It's possible to set as last parameter one specific brand (multiple will follow).
But I can't release it now, because I can't test it.
I think the many request to tankerkoenig from use of the widget killed their limits 😆 
I got an error if I open the API page "503 Service Temporarily Unavailable -Rate Limit Exceeded - Contact info@tankerkoenig.de" 😆 

I will test it and release it tomorrow.

Edit:
Ok i logged off the wifi and use 4G
They block IPs if API is used excessive.

**Comment by Necriso** [comment]
Released v1.1.4
Now you can add a specific brand
Check Readme.md for configuration
